export const boligselskaper = [
    {
        type: 'Kontakt',
        kartotekId: 33218,
        navn: 'Anders Rommetvedt Malmo',
        mobiltelefon: '48606151',
        epost: 'anders@malmoit.no',
        brukerId: 125883,
        brukernavn: 'arm',
        rolleId: 2,
        rolle: 'Redaktør',
        styreleder: false,
        styrelederTilgang: false,
        brlId: 3677,
        boligselskap: 'Demo utvikling',
        bblId: 3677,
        boligbyggelag: 'Boligbyggelag for uttesting',
    },
]

export const sjekkliste = [
    {
        sjekklisteMalId: 65306,
        tittel: 'Blokk 1-Egenkontroll bygning',
    },
    {
        sjekklisteMalId: 65307,
        tittel: 'HMS-runde - ansattes arbeidsmiljø',
    },
    {
        sjekklisteMalId: 65308,
        tittel: 'Lekeplass månedlig tilstandskontroll',
    },
    {
        sjekklisteMalId: 65309,
        tittel: 'Lekeplass - årlig kontroll',
    },
    {
        sjekklisteMalId: 65310,
        tittel: 'Tilfluktsrom - årlig kontroll',
    },
]

export const skjemasamling = [
    {
        skjemaSamlingId: 8,
        skjemaSamlingTypeId: 1,
        tittel: 'Branninstruks',
        filnavn: 'Branninstruks.doc',
        opprettet: '2010-06-01T00:00:00',
        endret: '2016-01-01T00:00:00',
        versjon: null,
        brlId: null,
        bblId: null,
        ansatte: null,
    },
    {
        skjemaSamlingId: 9,
        skjemaSamlingTypeId: 1,
        tittel: 'Egenmeldingsskjema',
        filnavn: 'Egenmeldingsskjema.doc',
        opprettet: '2010-06-01T00:00:00',
        endret: '2016-01-01T00:00:00',
        versjon: null,
        brlId: null,
        bblId: null,
        ansatte: true,
    },
    {
        skjemaSamlingId: 10,
        skjemaSamlingTypeId: 1,
        tittel: 'HMS-informasjon til beboer - Word',
        filnavn: 'HMS-informasjon til beboer v_24.05.2022.docx',
        opprettet: '2010-06-01T00:00:00',
        endret: '2022-05-24T00:00:00',
        versjon: '6',
        brlId: null,
        bblId: null,
        ansatte: false,
    },
    {
        skjemaSamlingId: 11,
        skjemaSamlingTypeId: 1,
        tittel: 'Oppfølgingsplan',
        filnavn: 'Oppfølgingsplan NAV.pdf',
        opprettet: '2010-06-01T00:00:00',
        endret: '2021-11-16T00:00:00',
        versjon: '4',
        brlId: null,
        bblId: null,
        ansatte: true,
    },
    {
        skjemaSamlingId: 12,
        skjemaSamlingTypeId: 1,
        tittel: 'Orientering til nyansatt',
        filnavn: 'Orientering til nyansatt.doc',
        opprettet: '2010-06-01T00:00:00',
        endret: '2016-01-01T00:00:00',
        versjon: null,
        brlId: null,
        bblId: null,
        ansatte: true,
    },
    {
        skjemaSamlingId: 13,
        skjemaSamlingTypeId: 1,
        tittel: 'Skjema medarbeidersamtale',
        filnavn: 'Skjema medarbeidersamtale.rtf',
        opprettet: '2010-06-01T00:00:00',
        endret: '2016-01-01T00:00:00',
        versjon: null,
        brlId: null,
        bblId: null,
        ansatte: true,
    },
    {
        skjemaSamlingId: 14,
        skjemaSamlingTypeId: 1,
        tittel: 'Arbeidsavtale (standard) fra arbeidstilsynet - Flere språk',
        filnavn: 'Standard arbeidsavtale fra Arbeidstilsynet - Flere språk.pdf',
        opprettet: '2021-11-16T00:00:00',
        endret: '2021-11-16T11:28:35.13',
        versjon: '1',
        brlId: null,
        bblId: null,
        ansatte: true,
    },
    {
        skjemaSamlingId: 16,
        skjemaSamlingTypeId: 1,
        tittel: 'Stillingsinstruks vaktmester',
        filnavn: 'Stillingsinstruks vaktmester.doc',
        opprettet: '2010-06-01T00:00:00',
        endret: '2016-01-01T00:00:00',
        versjon: null,
        brlId: null,
        bblId: null,
        ansatte: null,
    },
    {
        skjemaSamlingId: 127,
        skjemaSamlingTypeId: 1,
        tittel: 'Instruks ved gasslekkasje',
        filnavn: 'Instruks ved gasslekkasje.docx',
        opprettet: '2014-01-27T00:00:00',
        endret: '2016-01-01T00:00:00',
        versjon: null,
        brlId: null,
        bblId: null,
        ansatte: null,
    },
]

export const ansvarligPerson = [
    {
        navn: 'Styreleder',
        kartotekId: 31839,
        gruppe: 'Skjult',
    },
    {
        navn: 'Jesper Pedersen',
        kartotekId: 29951,
        gruppe: 'BBL',
    },
    {
        navn: 'Per Ole Mathisen',
        kartotekId: 4677,
        gruppe: 'BBL',
    },
    {
        navn: 'Ragnhild Aarekol',
        kartotekId: 19980,
        gruppe: 'BBL',
    },
    {
        navn: 'TestVaktmester',
        kartotekId: 32094,
        gruppe: 'BBL',
    },
    {
        navn: 'Anders Rommetvedt Malmo',
        kartotekId: 33218,
        gruppe: 'BRL',
    },
    {
        navn: 'Anders Ullnæs',
        kartotekId: 31841,
        gruppe: 'BRL',
    },
    {
        navn: 'Joachim Eide Eivindsen',
        kartotekId: 36741,
        gruppe: 'BRL',
    },
    {
        navn: 'Kristian Hyllestad',
        kartotekId: 31838,
        gruppe: 'BRL',
    },
    {
        navn: 'Richard Rørmark',
        kartotekId: 31840,
        gruppe: 'BRL',
    },
    {
        navn: 'Stian Storrvik',
        kartotekId: 31842,
        gruppe: 'BRL',
    },
]


/* CHANGELOG */
/*
- Changed varsling from string to int
- Renamed 'aktivitet' to 'beskrivelse' 
*/
export const aktivitetsmaler = [
    {
        aktivitetVeiviserId: 1,
        frist: null,
        tittel: 'Årlig HMS-gjennomgang',
        beskrivelse:
            'Årlig gjennomgang av HMS-systemet utføres ved HMS-rådgiver i boligbyggelaget. Rapport etter gjennomgang lagres i arkiv.',
        aktivitetRepetisjonId: null,
        varsling: 21,
        start: '1 år',
        ansvarlig: 'Styreleder',
        repetisjon: 'Hvert år',
        kravId: null,
        lovkrav: null,
        sjekklisteMaler: null,
        vedlegg: null,
        skjemaSamlinger: null,
    },
    {
        aktivitetVeiviserId: 2,
        frist: null,
        tittel: 'HMS-runde',
        beskrivelse:
            'Gjennomgang av HMS-forholdene for de ansatte. En kombinasjon av fysisk kartlegging og samtale.',
        aktivitetRepetisjonId: null,
        varsling: 7,
        start: '2 mnd',
        ansvarlig: 'Styreleder',
        repetisjon: 'Hvert år',
        kravId: null,
        lovkrav: null,
        sjekklisteMaler: null,
        vedlegg: null,
        skjemaSamlinger: null,
    },
    {
        aktivitetVeiviserId: 3,
        frist: null,
        tittel: 'Medarbeidersamtale',
        beskrivelse:
            'En til en samtale mellom den som er bemyndighet personalansvaret i boligselskapet og de ansatte. Referat skrives i forbindelse med samtalen.',
        aktivitetRepetisjonId: null,
        varsling: 14,
        start: '3 mnd',
        ansvarlig: 'Styreleder',
        repetisjon: 'Hvert år',
        kravId: null,
        lovkrav: null,
        sjekklisteMaler: null,
        vedlegg: null,
        skjemaSamlinger: null,
    },
    {
        aktivitetVeiviserId: 4,
        frist: null,
        tittel: 'Førstehjelpsopplæring',
        beskrivelse: 'De ansatte bør undervises i førstehjelp hvert annet år.',
        aktivitetRepetisjonId: null,
        varsling: 70,
        start: '6 mnd',
        ansvarlig: 'Styreleder',
        repetisjon: 'Hvert 2 år',
        kravId: null,
        lovkrav: null,
        sjekklisteMaler: null,
        vedlegg: null,
        skjemaSamlinger: null,
    },
    {
        aktivitetVeiviserId: 5,
        frist: null,
        tittel: 'Brannvernopplæring',
        beskrivelse:
            'De ansatte undervises i brannslokking hvert annet år. For særskilte brannobjekt er det et krav, for øvrige objekt er dette et valg.',
        aktivitetRepetisjonId: null,
        varsling: 50,
        start: '9 mnd',
        ansvarlig: 'Styreleder',
        repetisjon: 'Hvert 2 år',
        kravId: null,
        lovkrav: null,
        sjekklisteMaler: null,
        vedlegg: null,
        skjemaSamlinger: null,
    },
    {
        aktivitetVeiviserId: 6,
        frist: null,
        tittel: 'Opplæring i varmt arbeid',
        beskrivelse:
            'For arbeid med sveising, skjæring, sliping på andre plasser en faste arbeidsplasser kreves kurs i varmt arbeid.',
        aktivitetRepetisjonId: null,
        varsling: 50,
        start: '3 mnd',
        ansvarlig: 'Styreleder',
        repetisjon: 'Hvert 5 år',
        kravId: null,
        lovkrav: null,
        sjekklisteMaler: null,
        vedlegg: null,
        skjemaSamlinger: null,
    },
    {
        aktivitetVeiviserId: 7,
        frist: null,
        tittel: 'Bedriftshelsetjeneste',
        beskrivelse:
            'Hvert 2. år bør de ansatte gjennomgå en arbeidshelseundersøkelse. Tilbud om denne typen tjeneste hos en bedriftshelsetjeneste er noe en kan velge å gi de ansatte.',
        aktivitetRepetisjonId: null,
        varsling: 30,
        start: '6 mnd',
        ansvarlig: 'Styreleder',
        repetisjon: 'Hvert 2 år',
        kravId: null,
        lovkrav: null,
        sjekklisteMaler: null,
        vedlegg: null,
        skjemaSamlinger: null,
    },
    {
        aktivitetVeiviserId: 8,
        frist: null,
        tittel: 'Arbeidsutstyr - service',
        beskrivelse:
            'For enkelte typer arbeidsutstyr kreves det jevnlig eksternt tilsyn, mens for annet avgjør boligselskapet selv hvordan utstyret blir vedlikeholdt. Se artikkel om arbeidsutstyr.',
        aktivitetRepetisjonId: null,
        varsling: 14,
        start: '4 mnd',
        ansvarlig: 'Styreleder',
        repetisjon: 'Hvert år',
        kravId: null,
        lovkrav: null,
        sjekklisteMaler: null,
        vedlegg: null,
        skjemaSamlinger: null,
    },
    {
        aktivitetVeiviserId: 9,
        frist: null,
        tittel: 'Årlig informasjon til beboere',
        beskrivelse:
            'Årlig sendes alle boenheter informasjon om plikter den enkelte har i forbindelse med tilsyn i egen leilighet. Se forslag til skriv i skjemasamling i HMS-håndbok.',
        aktivitetRepetisjonId: null,
        varsling: 14,
        start: '5 mnd',
        ansvarlig: 'Styreleder',
        repetisjon: 'Hvert år',
        kravId: null,
        lovkrav: null,
        sjekklisteMaler: null,
        vedlegg: null,
        skjemaSamlinger: null,
    },
    {
        aktivitetVeiviserId: 10,
        frist: null,
        tittel: 'Batteri til røykvarslere',
        beskrivelse:
            'Utdeling av 1 stk batteri til røykvarsler i hver leilighet. I utgangspunktet har beboer selv ansvar for skifte av batteri i røykvarsler. Styret i boligselskapet har valgt å gjøre dette til et årlig tiltak.',
        aktivitetRepetisjonId: null,
        varsling: 30,
        start: '5 mnd',
        ansvarlig: 'Styreleder',
        repetisjon: 'Hvert år',
        kravId: null,
        lovkrav: null,
        sjekklisteMaler: null,
        vedlegg: null,
        skjemaSamlinger: null,
    },
    {
        aktivitetVeiviserId: 11,
        frist: null,
        tittel: 'Brannvern - kontroll i boenheter',
        beskrivelse:
            'Hvert 5 år gis tilbud om kontroll (service/utskiftning) av boenhetenes brannslokkeutstyr.',
        aktivitetRepetisjonId: null,
        varsling: 30,
        start: '1 år',
        ansvarlig: 'Styreleder',
        repetisjon: 'Hvert 5 år',
        kravId: null,
        lovkrav: null,
        sjekklisteMaler: null,
        vedlegg: null,
        skjemaSamlinger: null,
    },
    {
        aktivitetVeiviserId: 12,
        frist: null,
        tittel: 'Elektrisk - sakyndig kontroll',
        beskrivelse:
            'Hvert 5. år anbefales det å gjennomføre en sakkyndig kontroll av fellesarealer ved elektroinstallatør. Det bør tilrettelegges slik at samme sikkerhetskontroll kan gjennomføres for alle leiligheter. Ta kontakt med boligbyggelaget for ytterligere informasjon.',
        aktivitetRepetisjonId: null,
        varsling: 30,
        start: '2 år',
        ansvarlig: 'Styreleder',
        repetisjon: 'Hvert 5 år',
        kravId: null,
        lovkrav: null,
        sjekklisteMaler: null,
        vedlegg: null,
        skjemaSamlinger: null,
    },
    {
        aktivitetVeiviserId: 13,
        frist: null,
        tittel: 'Vannsjekk - sakkyndig kontroll',
        beskrivelse:
            'Hvert 5. år anbefales det å gjennomføre en kontrollrunde av både fellesarealer og leiligheter med tanke på forebygging av vannlekkasje. Ved vannsjekk utført av godkjent fagperson, vil denne kontrollen kunne redusere forsikringspremien til boligselskapet. Ta kontakt med boligbyggelaget for ytterligere informasjon og tilbud.',
        aktivitetRepetisjonId: null,
        varsling: 30,
        start: '3 år',
        ansvarlig: 'Styreleder',
        repetisjon: 'Hvert 5 år',
        kravId: null,
        lovkrav: null,
        sjekklisteMaler: null,
        vedlegg: null,
        skjemaSamlinger: null,
    },
    {
        aktivitetVeiviserId: 14,
        frist: null,
        tittel: 'Fyrrom - service',
        beskrivelse:
            'Service av fyringsanlegg og eventuelt nedgravd oljetank utføres av sakkyndig personell (fyringstekniker).',
        aktivitetRepetisjonId: null,
        varsling: 7,
        start: '2 mnd',
        ansvarlig: 'Styreleder',
        repetisjon: 'Hvert år',
        kravId: null,
        lovkrav: null,
        sjekklisteMaler: null,
        vedlegg: null,
        skjemaSamlinger: null,
    },
    {
        aktivitetVeiviserId: 15,
        frist: null,
        tittel: 'Heis - service',
        beskrivelse:
            'Service av heis utføres av sakkyndig firma. Frekvens/repetisjon for aktivitet endres i henhold til avtale med heisfirma.',
        aktivitetRepetisjonId: null,
        varsling: 7,
        start: '3 mnd',
        ansvarlig: 'Styreleder',
        repetisjon: 'Hvert år',
        kravId: null,
        lovkrav: null,
        sjekklisteMaler: null,
        vedlegg: null,
        skjemaSamlinger: null,
    },
    {
        aktivitetVeiviserId: 16,
        frist: null,
        tittel: 'Ventilasjonsanlegg - service',
        beskrivelse:
            'Service på ventilasjonsanlegget. Blant annet skal filter skiftes jevnlig.',
        aktivitetRepetisjonId: null,
        varsling: 14,
        start: '2 mnd',
        ansvarlig: 'Styreleder',
        repetisjon: 'Hver 6 mnd.',
        kravId: null,
        lovkrav: null,
        sjekklisteMaler: null,
        vedlegg: null,
        skjemaSamlinger: null,
    },
    {
        aktivitetVeiviserId: 17,
        frist: null,
        tittel: 'Fjernvarme - service',
        beskrivelse:
            'Service på fjernvarmeanlegg utføres av sakkyndig personell.',
        aktivitetRepetisjonId: null,
        varsling: 7,
        start: '2 mnd',
        ansvarlig: 'Styreleder',
        repetisjon: 'Hvert år',
        kravId: null,
        lovkrav: null,
        sjekklisteMaler: null,
        vedlegg: null,
        skjemaSamlinger: null,
    },
    {
        aktivitetVeiviserId: 18,
        frist: null,
        tittel: 'Egenkontroll av bygning',
        beskrivelse:
            'For å tilfredsstille krav til å føre tilsyn med fellesarealer og bygningene i boligselskapet utføres blant annet egenkontroll. Se egen sjekkliste for bygning.',
        aktivitetRepetisjonId: null,
        varsling: 7,
        start: '2 mnd',
        ansvarlig: 'Styreleder',
        repetisjon: 'Hvert halvår',
        kravId: null,
        lovkrav: null,
        sjekklisteMaler: null,
        vedlegg: null,
        skjemaSamlinger: null,
    },
    {
        aktivitetVeiviserId: 19,
        frist: null,
        tittel: 'Lekeplass(er) - tilstandskontroll',
        beskrivelse:
            'Jevnlig utføres en tilstandskontroll av lekeplass(er), se egen sjekkliste. Sjekkliste arkiveres i arkiv. Det anbefales i utgangpunktet en månedlig kontroll. Se i HMS-håndbok for kriterier som bør vurderes ved valg av sjeldnere hyppighet.',
        aktivitetRepetisjonId: null,
        varsling: 3,
        start: '1 mnd',
        ansvarlig: 'Styreleder',
        repetisjon: 'Hver mnd.',
        kravId: null,
        lovkrav: null,
        sjekklisteMaler: null,
        vedlegg: null,
        skjemaSamlinger: null,
    },
    {
        aktivitetVeiviserId: 20,
        frist: null,
        tittel: 'Lekeplass(er) - årlig kontroll',
        beskrivelse:
            'Årlig bør det utføres en mer detaljert kontroll av lekeplassen. Det anbefales at denne kontrollen utføres av en sakkyndig person. Se egen sjekkliste.',
        aktivitetRepetisjonId: null,
        varsling: 30,
        start: '1 år',
        ansvarlig: 'Styreleder',
        repetisjon: 'Hvert år',
        kravId: null,
        lovkrav: null,
        sjekklisteMaler: null,
        vedlegg: null,
        skjemaSamlinger: null,
    },
    {
        aktivitetVeiviserId: 21,
        frist: null,
        tittel: 'Leie av ekstra avfallscontainere',
        beskrivelse:
            'For å gi beboerne mulighet til å rydde opp i boder, kjeller og loft leies inn ekstra containere 1 gang i året. I forkant sendes ut skriv til alle beboere om tid og sted.',
        aktivitetRepetisjonId: null,
        varsling: 30,
        start: '3 mnd',
        ansvarlig: 'Styreleder',
        repetisjon: 'Hvert år',
        kravId: null,
        lovkrav: null,
        sjekklisteMaler: null,
        vedlegg: null,
        skjemaSamlinger: null,
    },
    {
        aktivitetVeiviserId: 22,
        frist: null,
        tittel: 'Dugnad',
        beskrivelse:
            'I forkant av dugnad sendes informasjon ut til alle beboere om tid og sted og arbeidet planlegges med tanke på utstyr og eventuelle innkjøp.',
        aktivitetRepetisjonId: null,
        varsling: 30,
        start: '3 mnd',
        ansvarlig: 'Styreleder',
        repetisjon: 'Hvert år',
        kravId: null,
        lovkrav: null,
        sjekklisteMaler: null,
        vedlegg: null,
        skjemaSamlinger: null,
    },
    {
        aktivitetVeiviserId: 23,
        frist: null,
        tittel: 'Heiskontroll',
        beskrivelse:
            'Hvert 2 år skal det gjennomføres kontroll av heis. Dette utføres av Norsk heiskontroll (Oslo kommune har egen kommunal heiskontrollordning). Styret må forsikre seg om at slik kontroll er blitt utført samt registrere og følge opp eventuelle avvik.',
        aktivitetRepetisjonId: null,
        varsling: 7,
        start: '4 mnd',
        ansvarlig: 'Styreleder',
        repetisjon: 'Hvert 2 år',
        kravId: null,
        lovkrav: null,
        sjekklisteMaler: null,
        vedlegg: null,
        skjemaSamlinger: null,
    },
    {
        aktivitetVeiviserId: 24,
        frist: null,
        tittel: 'Brannøvelse / informasjon brannvern',
        beskrivelse:
            'Det anbefales at det gjennomføres brannøvelse, og/eller et informasjonsmøte om brannvern. Dersom bygningen er særskilt brannobjekt er det et direkte krav til brannøvelse. For bistand til gjennomføring kan det tas kontakt med det lokale brannvesen eller firma innen brannvern. Se også www.branvernuka.no for råd og tips.',
        aktivitetRepetisjonId: null,
        varsling: 30,
        start: '6 mnd',
        ansvarlig: 'Styreleder',
        repetisjon: 'Hvert år',
        kravId: null,
        lovkrav: null,
        sjekklisteMaler: null,
        vedlegg: null,
        skjemaSamlinger: null,
    },
    {
        aktivitetVeiviserId: 25,
        frist: null,
        tittel: 'Brannvern - kontroll av fellesarealer',
        beskrivelse:
            'Årlig gjennomføres kontroll av brannslokkeutstyr som er plassert i fellesarealer. Utføres av person med kompetansebevis. Samtidig vurderes merking/skilting, rømningsveier og røykvarslere.',
        aktivitetRepetisjonId: null,
        varsling: 30,
        start: '3 mnd',
        ansvarlig: 'Styreleder',
        repetisjon: 'Hvert år',
        kravId: null,
        lovkrav: null,
        sjekklisteMaler: null,
        vedlegg: null,
        skjemaSamlinger: null,
    },
    {
        aktivitetVeiviserId: 26,
        frist: null,
        tittel: 'Brannalarm - ettersyn',
        beskrivelse:
            'Egenkontroll (ettersyn) av brannalarmanlegg. Sjekke at det ikke er feilmeldinger. I tilfelle feilmeldinger eller utkoblet anlegg ta kontakt for service. (Ved funksjonstest av anlegget utføres dette i samråd med firma som har service på anlegget. Beboere varsles i god tid).',
        aktivitetRepetisjonId: null,
        varsling: 7,
        start: '1 mnd',
        ansvarlig: 'Styreleder',
        repetisjon: 'Hver mnd.',
        kravId: null,
        lovkrav: null,
        sjekklisteMaler: null,
        vedlegg: null,
        skjemaSamlinger: null,
    },
    {
        aktivitetVeiviserId: 27,
        frist: null,
        tittel: 'Brannalarm - årlig kontroll',
        beskrivelse:
            'Årlig kontroll utføres av firma med nødvendig kompetanse om boligselskapets brannalarmanlegg. Ved alarmsentral som ikke er koblet til brannvesenet, gis nødvendig opplæring til instruert personell i boligselskapet for betjening av alarmsentral. Ved funksjonstest av anlegget varsles beboere i god tid.',
        aktivitetRepetisjonId: null,
        varsling: 30,
        start: '1 år',
        ansvarlig: 'Styreleder',
        repetisjon: 'Hvert år',
        kravId: null,
        lovkrav: null,
        sjekklisteMaler: null,
        vedlegg: null,
        skjemaSamlinger: null,
    },
    {
        aktivitetVeiviserId: 28,
        frist: null,
        tittel: 'Sprinkleranlegg - jevnlig ettersyn',
        beskrivelse:
            'Rutinemessig ettersyn og inspeksjon utføres av person med dokumentert opplæring. Rapport / sjekkliste etter ettersynet arkiveres. (Hyppighet / repetisjon tilpasses etter leverandørs anvisning.)',
        aktivitetRepetisjonId: null,
        varsling: 1,
        start: '1 mnd',
        ansvarlig: 'Styreleder',
        repetisjon: 'Hver mnd.',
        kravId: null,
        lovkrav: null,
        sjekklisteMaler: null,
        vedlegg: null,
        skjemaSamlinger: null,
    },
    {
        aktivitetVeiviserId: 29,
        frist: null,
        tittel: 'Sprinkleranlegg - årlig kontroll',
        beskrivelse:
            'Årlig kontroll av sprinkleranlegget utføres av sakkyndig firma. Rapport etter utført kontroll registreres i ESS av firma som utfører kontrollen. Rapport etter kontroll sendes boligselskapet. (Annet intervall kan være aktuelt, følg leverandørs anvisning.)',
        aktivitetRepetisjonId: null,
        varsling: 30,
        start: '6 mnd',
        ansvarlig: 'Styreleder',
        repetisjon: 'Hvert år',
        kravId: null,
        lovkrav: null,
        sjekklisteMaler: null,
        vedlegg: null,
        skjemaSamlinger: null,
    },
    {
        aktivitetVeiviserId: 30,
        frist: null,
        tittel: 'Tilfluktsrom - test av nødstrømsaggregat',
        beskrivelse:
            'Hver 3 måned prøvekjøres nødstrømsaggregat av kompetent person. Kjøretiden er 3 timer og satt for å hindre kondens, spesielt i avgassledninger, med påfølgende korrosjon. Utført test loggføres.',
        aktivitetRepetisjonId: null,
        varsling: 2,
        start: '1 mnd',
        ansvarlig: 'Styreleder',
        repetisjon: 'Hver 3 mnd.',
        kravId: null,
        lovkrav: null,
        sjekklisteMaler: null,
        vedlegg: null,
        skjemaSamlinger: null,
    },
    {
        aktivitetVeiviserId: 31,
        frist: null,
        tittel: 'Tilfluktsrom - årlig kontroll / vedlikehold',
        beskrivelse:
            'Årlig utføres det kontroll og vedlikehold av tilfluktsrom for å sikre at verneevnen til rommet er intakt.',
        aktivitetRepetisjonId: null,
        varsling: 7,
        start: '8 mnd',
        ansvarlig: 'Styreleder',
        repetisjon: 'Hvert år',
        kravId: null,
        lovkrav: null,
        sjekklisteMaler: null,
        vedlegg: null,
        skjemaSamlinger: null,
    },
    {
        aktivitetVeiviserId: 32,
        frist: null,
        tittel: 'Gassanlegg – systematisk tilstandskontroll',
        beskrivelse:
            'Gjennomføring av systematisk tilstandskontroll er en mer omfattende sikkerhetskontroll av utstyret og anlegget og er i tillegg til ordinært vedlikehold. Kontrollen utføres av sakkyndig person eventuelt uavhengig kontrollør der det er krav om dette. Omfang og hyppighet av kontroll bestemmes ut fra risiko, utstyret- og anleggets driftsbetingelser m.m. (Hyppighet / repetisjon tilpasses av boligselskapet etter leverandørs anvisning.)',
        aktivitetRepetisjonId: null,
        varsling: 60,
        start: '4 mnd',
        ansvarlig: 'Styreleder',
        repetisjon: 'Hvert år',
        kravId: null,
        lovkrav: null,
        sjekklisteMaler: null,
        vedlegg: null,
        skjemaSamlinger: null,
    },
    {
        aktivitetVeiviserId: 33,
        frist: null,
        tittel: 'Årlig risikovurdering',
        beskrivelse:
            'Det skal finnes en risikovurdering innen helse, miljø og sikkerhet for boligselskapet. Dette er en oversikt over hva som kan gå galt, sannsynligheten for at det skjer, konsekvensen dersom det skjer og informasjon om eksisterende tiltak og forslag til eventuelle nye tiltak. En slik oversikt gir et samlet bilde og nyttig informasjon av HMS-situasjonen i boligselskapet. Vurderingen skal holdes oppdatert. Det er derfor anbefalt at det tas en årlig revisjon/oppdatering. Se risikomodul under hovedmenyen «Oppfølging».',
        aktivitetRepetisjonId: null,
        varsling: 30,
        start: '1 mnd',
        ansvarlig: 'Styreleder',
        repetisjon: 'Hvert år',
        kravId: null,
        lovkrav: null,
        sjekklisteMaler: null,
        vedlegg: null,
        skjemaSamlinger: null,
    },
    {
        aktivitetVeiviserId: 34,
        frist: null,
        tittel: 'Røykventilasjon – ettersyn',
        beskrivelse:
            'Ettersyn (egenkontroll) av røykventilasjon kan utføres av eier av bygning eller ekstern. Person som utfører ettersynet skal ha fått nødvendig opplæring av kompetent person. Kontrollskjema /-sjekkliste for ettersynet bør utarbeides av leverandør. Hyppighet for ettersyn er normalt fra månedlig til kvartalsvis. Det anbefales å følge leverandørs anvisning.',
        aktivitetRepetisjonId: null,
        varsling: '14',
        start: '1 mnd',
        ansvarlig: 'Styreleder',
        repetisjon: 'Hver 3 mnd.',
        kravId: null,
        lovkrav: null,
        sjekklisteMaler: null,
        vedlegg: null,
        skjemaSamlinger: null,
    },
    {
        aktivitetVeiviserId: 35,
        frist: null,
        tittel: 'Røykventilasjon – årlig kontroll',
        beskrivelse:
            'Årlig kontroll og service utføres som beskrevet av produsent/leverandør av kompetent person.',
        aktivitetRepetisjonId: null,
        varsling: 14,
        start: '1 år',
        ansvarlig: 'Styreleder',
        repetisjon: 'Hvert år',
        kravId: null,
        lovkrav: null,
        sjekklisteMaler: null,
        vedlegg: null,
        skjemaSamlinger: null,
    },
    {
        aktivitetVeiviserId: 36,
        frist: null,
        tittel: 'Ladesystem elbil – årlig kontroll',
        beskrivelse:
            'Det skal årlig utføres en kontroll av de ladeanlegg som boligselskapet eier eller har ansvar for. Dette skal utføres av kompetent elektrovirksomhet. Dokumentasjon på utført kontroll arkiveres.',
        aktivitetRepetisjonId: null,
        varsling: 7,
        start: '10 mnd',
        ansvarlig: 'Styreleder',
        repetisjon: 'Hvert år',
        kravId: null,
        lovkrav: null,
        sjekklisteMaler: null,
        vedlegg: null,
        skjemaSamlinger: null,
    },
    {
        aktivitetVeiviserId: 37,
        frist: null,
        tittel: 'Legionellakontroll',
        beskrivelse:
            'Det skal utføres jevnlig kontroll av felles varmtvannsanlegg for å forebygge fare for smitte av legionella. Eier av anlegget er ansvarlig. Kontroll av temperatur bør utføres jevnlig (månedlig). I tillegg utføres en utvidet kontroll med fagperson som rørlegger eller annet spesialfirma (risikovurdering, kontroll og behandling av røranlegg m.m.). Hvor ofte utvidet kontroll bør utføres vil avhenge av type anlegg og nødvendige tiltak. Det skal foreligge instrukser for drift og vedlikehold av varmtvannsanlegget.',
        aktivitetRepetisjonId: null,
        varsling: 7,
        start: '1 mnd',
        ansvarlig: 'Styreleder',
        repetisjon: 'Hver mnd.',
        kravId: null,
        lovkrav: null,
        sjekklisteMaler: null,
        vedlegg: null,
        skjemaSamlinger: null,
    },
    {
        aktivitetVeiviserId: 38,
        frist: null,
        tittel: 'Tilsyn og vedlikehold av hjertestarter',
        beskrivelse:
            'Hver sjette måned etterses hjertestarteren. Sjekk at batteriet er i orden og at elektrodene ikke har gått ut på dato. Utført vedlikehold, endringer og reparasjoner skal dokumenteres. Legg inn kommentar om tiltak som blir gjort, eventuelt at alt er OK når du behandler denne aktiviteten. (Dersom hjertestarteren er registrert i det offentlige hjertestarterregisteret vil du også få varsel hver sjette måned, som skal bekreftes om at din registrering av hjertestarter er korrekt. Vurder behovet for å gi tilbud om kurs i bruk av hjertestarter og hjerte- og lungeredning, se mer informasjon i artikkel i HMS-håndbok).',
        aktivitetRepetisjonId: null,
        varsling: 3,
        start: '6 mnd',
        ansvarlig: 'Styreleder',
        repetisjon: 'Hver 6 mnd.',
        kravId: null,
        lovkrav: null,
        sjekklisteMaler: null,
        vedlegg: null,
        skjemaSamlinger: null,
    },
]
