export const boligselskaper = [
    {
        type: 'Kontakt',
        kartotekId: 33218,
        navn: 'Anders Rommetvedt Malmo',
        mobiltelefon: '48606151',
        epost: 'anders@malmoit.no',
        brukerId: 125883,
        brukernavn: 'arm',
        rolleId: 2,
        rolle: 'Redaktør',
        styreleder: false,
        styrelederTilgang: false,
        brlId: 3677,
        boligselskap: 'Demo utvikling',
        bblId: 3677,
        boligbyggelag: 'Boligbyggelag for uttesting',
    },
]

export const sjekkliste = [
    {
        sjekklisteMalId: 65306,
        tittel: 'Blokk 1-Egenkontroll bygning',
    },
    {
        sjekklisteMalId: 65307,
        tittel: 'HMS-runde - ansattes arbeidsmiljø',
    },
    {
        sjekklisteMalId: 65308,
        tittel: 'Lekeplass månedlig tilstandskontroll',
    },
    {
        sjekklisteMalId: 65309,
        tittel: 'Lekeplass - årlig kontroll',
    },
    {
        sjekklisteMalId: 65310,
        tittel: 'Tilfluktsrom - årlig kontroll',
    },
]

export const skjemasamling = [
    {
        skjemaSamlingId: 8,
        skjemaSamlingTypeId: 1,
        tittel: 'Branninstruks',
        filnavn: 'Branninstruks.doc',
        opprettet: '2010-06-01T00:00:00',
        endret: '2016-01-01T00:00:00',
        versjon: null,
        brlId: null,
        bblId: null,
        ansatte: null,
    },
    {
        skjemaSamlingId: 9,
        skjemaSamlingTypeId: 1,
        tittel: 'Egenmeldingsskjema',
        filnavn: 'Egenmeldingsskjema.doc',
        opprettet: '2010-06-01T00:00:00',
        endret: '2016-01-01T00:00:00',
        versjon: null,
        brlId: null,
        bblId: null,
        ansatte: true,
    },
    {
        skjemaSamlingId: 10,
        skjemaSamlingTypeId: 1,
        tittel: 'HMS-informasjon til beboer - Word',
        filnavn: 'HMS-informasjon til beboer v_24.05.2022.docx',
        opprettet: '2010-06-01T00:00:00',
        endret: '2022-05-24T00:00:00',
        versjon: '6',
        brlId: null,
        bblId: null,
        ansatte: false,
    },
    {
        skjemaSamlingId: 11,
        skjemaSamlingTypeId: 1,
        tittel: 'Oppfølgingsplan',
        filnavn: 'Oppfølgingsplan NAV.pdf',
        opprettet: '2010-06-01T00:00:00',
        endret: '2021-11-16T00:00:00',
        versjon: '4',
        brlId: null,
        bblId: null,
        ansatte: true,
    },
    {
        skjemaSamlingId: 12,
        skjemaSamlingTypeId: 1,
        tittel: 'Orientering til nyansatt',
        filnavn: 'Orientering til nyansatt.doc',
        opprettet: '2010-06-01T00:00:00',
        endret: '2016-01-01T00:00:00',
        versjon: null,
        brlId: null,
        bblId: null,
        ansatte: true,
    },
    {
        skjemaSamlingId: 13,
        skjemaSamlingTypeId: 1,
        tittel: 'Skjema medarbeidersamtale',
        filnavn: 'Skjema medarbeidersamtale.rtf',
        opprettet: '2010-06-01T00:00:00',
        endret: '2016-01-01T00:00:00',
        versjon: null,
        brlId: null,
        bblId: null,
        ansatte: true,
    },
    {
        skjemaSamlingId: 14,
        skjemaSamlingTypeId: 1,
        tittel: 'Arbeidsavtale (standard) fra arbeidstilsynet - Flere språk',
        filnavn: 'Standard arbeidsavtale fra Arbeidstilsynet - Flere språk.pdf',
        opprettet: '2021-11-16T00:00:00',
        endret: '2021-11-16T11:28:35.13',
        versjon: '1',
        brlId: null,
        bblId: null,
        ansatte: true,
    },
    {
        skjemaSamlingId: 16,
        skjemaSamlingTypeId: 1,
        tittel: 'Stillingsinstruks vaktmester',
        filnavn: 'Stillingsinstruks vaktmester.doc',
        opprettet: '2010-06-01T00:00:00',
        endret: '2016-01-01T00:00:00',
        versjon: null,
        brlId: null,
        bblId: null,
        ansatte: null,
    },
    {
        skjemaSamlingId: 127,
        skjemaSamlingTypeId: 1,
        tittel: 'Instruks ved gasslekkasje',
        filnavn: 'Instruks ved gasslekkasje.docx',
        opprettet: '2014-01-27T00:00:00',
        endret: '2016-01-01T00:00:00',
        versjon: null,
        brlId: null,
        bblId: null,
        ansatte: null,
    },
]

export const ansvarligPerson = [
    {
        navn: 'Styreleder',
        kartotekId: 31839,
        gruppe: 'Skjult',
    },
    {
        navn: 'Jesper Pedersen',
        kartotekId: 29951,
        gruppe: 'BBL',
    },
    {
        navn: 'Per Ole Mathisen',
        kartotekId: 4677,
        gruppe: 'BBL',
    },
    {
        navn: 'Ragnhild Aarekol',
        kartotekId: 19980,
        gruppe: 'BBL',
    },
    {
        navn: 'TestVaktmester',
        kartotekId: 32094,
        gruppe: 'BBL',
    },
    {
        navn: 'Anders Rommetvedt Malmo',
        kartotekId: 33218,
        gruppe: 'BRL',
    },
    {
        navn: 'Anders Ullnæs',
        kartotekId: 31841,
        gruppe: 'BRL',
    },
    {
        navn: 'Joachim Eide Eivindsen',
        kartotekId: 36741,
        gruppe: 'BRL',
    },
    {
        navn: 'Kristian Hyllestad',
        kartotekId: 31838,
        gruppe: 'BRL',
    },
    {
        navn: 'Richard Rørmark',
        kartotekId: 31840,
        gruppe: 'BRL',
    },
    {
        navn: 'Stian Storrvik',
        kartotekId: 31842,
        gruppe: 'BRL',
    },
]
